import type {
  AdminManualQuarantineBacklog,
  AdminManualQuarantineBacklogItem,
  AdminManualQuarantineBacklogQuery,
} from "@/lib/admin-manual-quarantine-backlog";

export function manualQuarantineBacklogQuery(
  overrides: Partial<AdminManualQuarantineBacklogQuery> = {},
): AdminManualQuarantineBacklogQuery {
  return {
    activeViewId: null,
    ageBucket: null,
    clusterPage: 1,
    clusterPageSize: 20,
    domains: [],
    evidenceFailures: [],
    groupBy: "repair_group",
    owners: [],
    page: 2,
    pageSize: 25,
    policyReasons: [],
    repairs: [],
    search: "",
    snapshotAt: null,
    snapshotRevision: null,
    asOfAt: null,
    sort: "oldest",
    statuses: [],
    ...overrides,
  };
}

export function manualQuarantineBacklogItem(
  overrides: Partial<AdminManualQuarantineBacklogItem> = {},
): AdminManualQuarantineBacklogItem {
  return {
    ageBucket: "eight_to_thirty_days",
    ageDays: 18,
    assignedAt: null,
    assignedToEmail: null,
    assignedToUserId: null,
    awardHref: "/example-award",
    awardId: "10000000-0000-4000-8000-000000000001",
    awardName: "Example Award",
    awardSlug: "example-award",
    caseKey: "case-1",
    category: "public_page",
    evidenceFailureCode: "missing_baseline_evidence",
    evidenceFailureLabel: "Baseline image evidence is missing",
    evidenceHash: "a".repeat(64),
    evidenceRecordCount: 3,
    firstObservedAt: "2026-06-28T14:30:00.000Z",
    functionalOwner: "Evidence repair",
    id: "10000000-0000-4000-8000-000000000002",
    lastObservedAt: "2026-07-15T14:30:00.000Z",
    likelyRepairCode: "rehydrate_from_r2",
    likelyRepairLabel: "Rehydrate immutable evidence from R2",
    policyHash: "b".repeat(64),
    policyId: "manual-quarantine-v1",
    policyReasonCode: "last_known_good_protection",
    policyReasonLabel: "Last-known-good protection blocked publication",
    policyVersion: "2026.07.16",
    publicImpact: "blocked",
    quarantineKey: "quarantine-1",
    reason: "The immutable baseline image could not be loaded.",
    reasonCode: "missing_baseline_evidence",
    recommendedAction: "Verify R2 evidence, then rehydrate the local cache.",
    retryCharge: "none",
    retryMode: "manual_only",
    safeActions: {
      assignToMe: true,
      canResolve: false,
      canRetry: false,
      createsApiCharge: false,
      startReview: true,
      unassign: false,
    },
    severity: "high",
    sourceDomain: "example.org",
    sourceDomainBasis: "event_specific_source",
    sourceHref: "https://example.org/award",
    sourceId: "20000000-0000-4000-8000-000000000002",
    sourceUrl: "https://example.org/award",
    status: "quarantined",
    terminal: true,
    terminalFailureCount: 4,
    title: "Example Award baseline evidence",
    updatedAt: "2026-07-15T14:30:00.000Z",
    visualCandidateId: null,
    ...overrides,
  };
}

export function manualQuarantineBacklog(
  overrides: Partial<AdminManualQuarantineBacklog> = {},
): AdminManualQuarantineBacklog {
  const items = Array.from({ length: 25 }, (_, index) =>
    manualQuarantineBacklogItem({
      caseKey: `case-${index + 1}`,
      evidenceHash: index.toString(16).padStart(64, "0"),
      id: `10000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
      quarantineKey: `quarantine-${index + 1}`,
      title: `Example quarantine case ${index + 1}`,
    }),
  );
  return {
    asOf: "2026-07-16T18:00:00.000Z",
    backlogRevision: 17,
    chargeGatedCases: 12,
    clusterPage: 1,
    clusterPageCount: 1,
    clusterPageSize: 20,
    clusters: [
      {
        cases: 41,
        chargeGatedCases: 0,
        evidenceFailureCode: "missing_baseline_evidence",
        evidenceFailureLabel: "Baseline image evidence is missing",
        evidenceRecords: 79,
        key: "repair-group-one",
        label: "example.org · missing evidence · R2 rehydration",
        likelyRepairCode: "rehydrate_from_r2",
        likelyRepairLabel: "Rehydrate immutable evidence from R2",
        oldestObservedAt: "2026-06-28T14:30:00.000Z",
        policyReasonCode: "last_known_good_protection",
        policyReasonLabel: "Last-known-good protection blocked publication",
        sourceDomain: "example.org",
        terminalCases: 31,
        unassignedCases: 29,
      },
    ],
    countsAuthoritative: true,
    countsMatch: true,
    evidenceRecords: 452,
    exactClusterTotal: 11,
    exactTotal: 236,
    facets: {
      ages: [{ cases: 236, key: "eight_to_thirty_days", label: "8–30 days" }],
      domains: [{ cases: 41, key: "example.org", label: "example.org" }],
      evidenceFailures: [
        {
          cases: 41,
          key: "missing_baseline_evidence",
          label: "Baseline image evidence is missing",
        },
      ],
      owners: [{ cases: 200, key: "unassigned", label: "Unassigned" }],
      policyReasons: [
        {
          cases: 41,
          key: "last_known_good_protection",
          label: "Last-known-good protection blocked publication",
        },
      ],
      repairs: [
        {
          cases: 41,
          key: "rehydrate_from_r2",
          label: "Rehydrate immutable evidence from R2",
        },
      ],
      statuses: [{ cases: 236, key: "quarantined", label: "Quarantined" }],
    },
    groupBy: "repair_group",
    items,
    oldestObservedAt: "2026-06-28T14:30:00.000Z",
    page: 2,
    pageCount: 10,
    pageSize: 25,
    registryFresh: true,
    registryStateTotal: 236,
    registrySyncedAt: "2026-07-16T17:58:00.000Z",
    schemaVersion: "manual-quarantine-backlog-v1",
    sort: "oldest",
    terminalCases: 216,
    unassignedCases: 200,
    unfilteredExactTotal: 236,
    ...overrides,
  };
}
