-- Blocking regression audits keep the activated release live (owner directive
-- 2026-09-02/03). private.invalidate_stage1_release_for_regression_audit runs
-- from record_shared_award_regression_audit on every failed/critical
-- regression observation (the Page Audit Lane, every 15 min). It demoted the
-- cohort and, whenever the release row read verified_beta, cleared every
-- cohort's release epoch and reset the release row to revalidation_pending
-- with activated_at null - a full yank of the live site from one alias
-- award's deadline conflict, with no activated-release guard. Under the
-- activated release the audit is now recorded and the cohort flagged for
-- re-verification; nothing else changes. Pre-activation behaviour unchanged.
-- Generated by patching the live definition; only the guard block was added.

CREATE OR REPLACE FUNCTION private.invalidate_stage1_release_for_regression_audit(p_shared_award_id uuid, p_regression_audit_id uuid, p_observation_key text, p_blocked_at timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_cohort_key text;
  v_registry public.stage1_award_registry%rowtype;
  v_release public.stage1_publication_release_state%rowtype;
  v_regression_audit public.shared_award_page_audits%rowtype;
  v_deterministic_audit_id uuid;
  v_award_invalidated boolean := false;
  v_release_invalidated boolean := false;
  v_rejected_acceptances integer := 0;
  v_cleared_release_epochs integer := 0;
  v_additional_cleared_release_epochs integer := 0;
  v_reason text;
  v_evidence jsonb;
begin
  if p_shared_award_id is null
    or p_regression_audit_id is null
    or p_observation_key is null
    or p_observation_key !~ '^[0-9a-f]{64}$'
    or p_blocked_at is null then
    raise exception using
      errcode = '22023',
      message = 'Stage 1 regression invalidation requires an award, audit, observation key, and timestamp.';
  end if;

  -- Always take the national fence before an audit, award, registry, or
  -- release row lock. The caller normally already owns it, so this is a
  -- cheap re-entrant guard that also makes the private helper safe in
  -- isolation.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stage1-national-25-release', 0)
  );

  select * into v_regression_audit
  from public.shared_award_page_audits audit
  where audit.id = p_regression_audit_id
    and audit.shared_award_id = p_shared_award_id
    and audit.audit_kind = 'regression'
    and audit.resolved_at is null
    and audit.public_page_snapshot ->> 'observation_key' = p_observation_key
    and (
      audit.audit_status in ('failed', 'needs_review')
      or audit.severity in ('error', 'critical')
    )
  for update;
  if not found then
    raise exception using
      errcode = '23514',
      message = 'Stage 1 regression invalidation requires the exact unresolved blocking regression observation.';
  end if;

  select member.cohort_key
  into v_cohort_key
  from public.stage1_award_members member
  where member.shared_award_id = p_shared_award_id;

  if v_cohort_key is null then
    return pg_catalog.jsonb_build_object(
      'affected_stage1_cohort', false,
      'award_invalidated', false,
      'national_release_invalidated', false,
      'ready_acceptances_rejected', 0,
      'release_epochs_cleared', 0
    );
  end if;

  select * into v_registry
  from public.stage1_award_registry registry
  where registry.cohort_key = v_cohort_key
  for update;
  if not found then
    raise exception using
      errcode = '23503',
      message = 'The affected Stage 1 registry row does not exist.';
  end if;

  select * into v_release
  from public.stage1_publication_release_state release_state
  where release_state.release_key = 'stage1-national-25'
  for update;
  if not found then
    raise exception using
      errcode = '23514',
      message = 'The authoritative Stage 1 national release row does not exist.';
  end if;

  select audit.id
  into v_deterministic_audit_id
  from public.shared_award_page_audits audit
  where audit.shared_award_id = v_registry.canonical_shared_award_id
    and audit.audit_kind = 'deterministic'
  order by audit.created_at desc, audit.id desc
  limit 1;

  update public.stage1_release_acceptance_records acceptance
  set status = 'rejected'
  where acceptance.release_key = 'stage1-national-25'
    and acceptance.status = 'ready';
  get diagnostics v_rejected_acceptances = row_count;

  v_reason := pg_catalog.format(
    'Blocking regression audit %s requires verified Stage 1 revalidation.',
    p_regression_audit_id
  );
  v_evidence := pg_catalog.jsonb_build_object(
    'invalidation_contract', 'stage1-blocking-regression-v1',
    'blocked_at', p_blocked_at,
    'cohort_key', v_cohort_key,
    'affected_shared_award_id', p_shared_award_id,
    'regression', pg_catalog.jsonb_build_object(
      'audit_id', p_regression_audit_id,
      'audit_kind', v_regression_audit.audit_kind,
      'audit_status', v_regression_audit.audit_status,
      'severity', v_regression_audit.severity,
      'observation_key', p_observation_key
    ),
    'deterministic_publication', pg_catalog.jsonb_build_object(
      'canonical_shared_award_id', v_registry.canonical_shared_award_id,
      'audit_kind', 'deterministic',
      'page_audit_id', v_deterministic_audit_id,
      'fact_ledger_batch_id', v_registry.fact_ledger_batch_id,
      'evidence_checked_at', v_registry.evidence_checked_at,
      'last_verified_at', v_registry.last_verified_at
    ),
    'previous_award_state', v_registry.publication_state,
    'previous_award_release_epoch', v_registry.release_epoch,
    'previous_national_state', v_release.release_state,
    'previous_national_release_epoch', v_release.release_epoch,
    'ready_acceptances_rejected', v_rejected_acceptances
  );

  -- OWNER DIRECTIVE 2026-09-02/03 (publish now, refine daily): while the
  -- national release is ACTIVATED, a blocking regression audit is recorded and
  -- flagged for re-verification, but it neither demotes the cohort nor yanks
  -- the release. Pre-activation behaviour (below) is unchanged, and the audit
  -- row itself stays unresolved for the operator. Observed 2026-09-03: three
  -- alias awards (boren, gaither, rhodes) deterministically evaluate
  -- failed/critical on deadline conflicts every ~15h; the first such block
  -- after activation would have cleared every cohort's epoch and set the
  -- release row back to revalidation_pending, darkening all 25 pages.
  if v_release.activated_at is not null
    and v_release.release_state = 'verified_beta'
    and v_release.release_epoch is not null
    and v_registry.publication_state = 'verified_beta'
    and v_registry.release_epoch = v_release.release_epoch
  then
    update public.stage1_award_registry registry
    set
      state_reason = v_reason
        || ' Re-verification is scheduled while the last verified publication stays live (activated release preserved).',
      updated_at = p_blocked_at
    where registry.cohort_key = v_cohort_key;

    return pg_catalog.jsonb_build_object(
      'affected_stage1_cohort', true,
      'cohort_key', v_cohort_key,
      'award_invalidated', false,
      'national_release_invalidated', false,
      'activated_release_preserved', true,
      'ready_acceptances_rejected', v_rejected_acceptances,
      'release_epochs_cleared', 0,
      'deterministic_page_audit_id', v_deterministic_audit_id,
      'deterministic_fact_ledger_batch_id', v_registry.fact_ledger_batch_id,
      'regression_audit_id', p_regression_audit_id,
      'regression_observation_key', p_observation_key
    );
  end if;

  if v_registry.publication_state = 'verified_beta' then
    if v_registry.release_epoch is not null then
      v_cleared_release_epochs := 1;
    end if;
    update public.stage1_award_registry registry
    set
      publication_state = 'revalidation_pending',
      state_reason = v_reason,
      release_epoch = null,
      updated_at = p_blocked_at
    where registry.cohort_key = v_cohort_key;
    v_award_invalidated := true;

    insert into public.stage1_award_publication_events (
      cohort_key,
      previous_state,
      next_state,
      reason,
      policy_version,
      evidence_snapshot,
      evidence_hash,
      actor
    ) values (
      v_cohort_key,
      v_registry.publication_state,
      'revalidation_pending',
      v_reason,
      v_registry.policy_version,
      v_evidence,
      public.stage1_publication_evidence_hash(v_evidence),
      'scheduled_regression_audit'
    );
  end if;

  if v_release.release_state = 'verified_beta' then
    update public.stage1_award_registry registry
    set release_epoch = null, updated_at = p_blocked_at
    where registry.release_epoch is not null;
    get diagnostics v_additional_cleared_release_epochs = row_count;
    v_cleared_release_epochs :=
      v_cleared_release_epochs + v_additional_cleared_release_epochs;

    update public.stage1_publication_release_state release_state
    set
      release_state = 'revalidation_pending',
      release_epoch = null,
      reason = v_reason,
      activated_at = null,
      updated_at = p_blocked_at
    where release_state.release_key = 'stage1-national-25';
    v_release_invalidated := true;

    v_evidence := v_evidence || pg_catalog.jsonb_build_object(
      'release_epochs_cleared', v_cleared_release_epochs
    );
    insert into public.stage1_publication_release_events (
      release_key,
      previous_state,
      next_state,
      release_epoch,
      reason,
      policy_version,
      cohort_identity_version,
      cohort_identity_hash,
      evidence_snapshot,
      evidence_hash,
      actor
    ) values (
      'stage1-national-25',
      v_release.release_state,
      'revalidation_pending',
      null,
      v_reason,
      v_release.policy_version,
      v_release.cohort_identity_version,
      v_release.cohort_identity_hash,
      v_evidence,
      public.stage1_publication_evidence_hash(v_evidence),
      'scheduled_regression_audit'
    );
  end if;

  return pg_catalog.jsonb_build_object(
    'affected_stage1_cohort', true,
    'cohort_key', v_cohort_key,
    'award_invalidated', v_award_invalidated,
    'national_release_invalidated', v_release_invalidated,
    'ready_acceptances_rejected', v_rejected_acceptances,
    'release_epochs_cleared', v_cleared_release_epochs,
    'deterministic_page_audit_id', v_deterministic_audit_id,
    'deterministic_fact_ledger_batch_id', v_registry.fact_ledger_batch_id,
    'regression_audit_id', p_regression_audit_id,
    'regression_observation_key', p_observation_key
  );
end;
$function$;
