-- Owner-directed early publication (2026-09-02): waive ONLY the four-night
-- fleet-soak leg of the Stage 1 release gate. Directed by the owner in
-- session (publish now, refine daily); executed by
-- codex-stage1-claude-operator-2026-08-31. Generated by dumping the live
-- pg_get_functiondef and patching the single soak clause - no other logic
-- touched. The original clause is preserved in the comment for restoration.

CREATE OR REPLACE FUNCTION private.stage1_gate_without_contact_fence_20260717123000(p_evaluated_at timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_now timestamptz := p_evaluated_at;
  v_target jsonb := private.stage1_release_production_target_snapshot();
  v_due_date date;
  v_identity_payload text;
  v_cohort_count bigint := 0;
  v_ready_count bigint := 0;
  v_cohort_identity_hash text;
  v_quarantine_count bigint := 0;
  v_invite_reissue_count bigint := 0;
  v_contract jsonb;
  v_contract_ok boolean := false;
  v_invite_acl_ok boolean := false;
  v_vault_access_contract_safe boolean := false;
  v_vault_service_profile_blocked boolean := false;
  v_contract_state_hash text;
  v_release public.stage1_publication_release_state%rowtype;
  v_runtime public.stage1_release_acceptance_artifacts%rowtype;
  v_rollback public.stage1_release_acceptance_artifacts%rowtype;
  v_leak public.stage1_release_acceptance_artifacts%rowtype;
  v_r2 public.stage1_release_acceptance_artifacts%rowtype;
  v_crop public.stage1_release_acceptance_artifacts%rowtype;
  v_objects jsonb;
  v_coverage jsonb;
  v_leak_manifest jsonb;
  v_r2_bound boolean := false;
  v_crop_bound boolean := false;
  v_artifacts_ok boolean := false;
  v_nightly jsonb := '{}'::jsonb;
  v_nightly_ok boolean := false;
  v_budgets jsonb := '[]'::jsonb;
  v_budget_count bigint := 0;
  v_budget_valid_count bigint := 0;
  v_budgets_ok boolean := false;
  v_lanes jsonb := '[]'::jsonb;
  v_lane_count bigint := 0;
  v_lane_valid_count bigint := 0;
  v_lanes_ok boolean := false;
  v_failures text[] := '{}'::text[];
  v_basis jsonb;
  v_state_hash text;
begin
  if v_now is null then
    raise exception using errcode = '22023', message = 'A release evaluation timestamp is required.';
  end if;
  v_due_date := case
    when (v_now at time zone 'America/Chicago')::time < time '18:00'
      then (v_now at time zone 'America/Chicago')::date - 1
    else (v_now at time zone 'America/Chicago')::date
  end;

  select
    count(*),
    pg_catalog.string_agg(
      pg_catalog.concat_ws(
        '|',
        registry.launch_rank::text,
        registry.cohort_key,
        registry.canonical_name,
        registry.canonical_shared_award_id::text,
        registry.canonical_slug,
        registry.official_homepage
      ),
      E'\n' order by registry.launch_rank
    )
  into v_cohort_count, v_identity_payload
  from public.stage1_award_registry registry;
  v_cohort_identity_hash := public.stage1_publication_evidence_hash(
    pg_catalog.to_jsonb(v_identity_payload)
  );
  select count(*) filter (
    where public.stage1_effective_publication_reason(
      registry.cohort_key, v_now
    ) = 'verified'
  ) into v_ready_count
  from public.stage1_award_registry registry;

  select count(*) into v_quarantine_count
  from public.manual_quarantine_registry quarantine
  where quarantine.classification = 'actionable_quarantine'
    and quarantine.requires_action
    and quarantine.status in ('quarantined', 'in_review')
    and (
      exists (
        select 1 from public.stage1_award_members member
        where member.shared_award_id = quarantine.shared_award_id
      )
      or exists (
        select 1
        from public.shared_award_sources source
        join public.stage1_award_members member
          on member.shared_award_id = source.shared_award_id
        where source.id = quarantine.shared_award_source_id
      )
      or exists (
        select 1
        from public.shared_award_visual_review_candidates candidate
        join public.stage1_award_members member
          on member.shared_award_id = candidate.shared_award_id
        where candidate.id = quarantine.visual_review_candidate_id
      )
    );

  v_contract := public.get_awardping_release_contract_status();
  v_contract_ok := v_contract ->> 'contract_version' = 'awardping-release-contract-v1'
    and v_contract ->> 'matches' = 'true'
    and v_contract ->> 'requirement_count' = '16'
    and pg_catalog.jsonb_typeof(v_contract -> 'missing') = 'array'
    and pg_catalog.jsonb_array_length(v_contract -> 'missing') = 0;
  select count(*) into v_invite_reissue_count
  from public.office_invite_security_reissues reissue
  where reissue.status in ('pending_reissue', 'replacement_ready');
  v_invite_acl_ok :=
    not pg_catalog.has_function_privilege(
      'anon', 'public.reserve_office_invite_signup(text)', 'EXECUTE'
    )
    and not pg_catalog.has_function_privilege(
      'authenticated', 'public.reserve_office_invite_signup(text)', 'EXECUTE'
    )
    and not pg_catalog.has_function_privilege(
      'anon', 'public.complete_office_invite_signup(uuid,uuid,uuid,text)', 'EXECUTE'
    )
    and not pg_catalog.has_function_privilege(
      'authenticated', 'public.complete_office_invite_signup(uuid,uuid,uuid,text)', 'EXECUTE'
    )
    and not pg_catalog.has_function_privilege(
      'anon', 'public.accept_office_invite_for_user(text,uuid,text)', 'EXECUTE'
    )
    and not pg_catalog.has_function_privilege(
      'authenticated', 'public.accept_office_invite_for_user(text,uuid,text)', 'EXECUTE'
    )
    and not exists (
      select 1
      from pg_catalog.pg_policies policy
      where policy.schemaname = 'public'
        and policy.tablename in ('offices', 'office_members')
        and policy.cmd in ('INSERT', 'ALL')
        and (
          'public' = any(policy.roles)
          or 'anon' = any(policy.roles)
          or 'authenticated' = any(policy.roles)
        )
    )
    and exists (
      select 1
      from pg_catalog.pg_trigger trigger
      where trigger.tgrelid = 'auth.users'::pg_catalog.regclass
        and trigger.tgname = 'on_auth_user_created'
        and not trigger.tgisinternal
        and trigger.tgenabled <> 'D'
    );

  v_vault_access_contract_safe := private.stage1_vault_access_contract_safe();
  v_vault_service_profile_blocked :=
    coalesce(v_runtime.evidence ->> 'vault_profile_http_status', '') = '406'
    and coalesce(v_runtime.evidence ->> 'vault_profile_postgrest_code', '') = 'PGRST106'
    and coalesce(v_runtime.evidence ->> 'vault_profile_exposed', '') = 'false'
    and coalesce(v_runtime.evidence ->> 'vault_profile_redirected', '') = 'false';
  v_contract_state_hash := private.stage1_release_contract_state_hash();
  select * into v_release
  from public.stage1_publication_release_state release
  where release.release_key = 'stage1-national-25';

  select * into v_runtime
  from private.stage1_current_valid_release_artifact(
    'hosted_runtime_identity', v_now
  ) artifact
  where artifact.completed_at >= v_now - interval '1 hour'
  limit 1;
  select * into v_rollback
  from private.stage1_current_valid_release_artifact('rollback_drill', v_now)
  limit 1;
  select * into v_leak
  from private.stage1_current_valid_release_artifact('non_cohort_leak_crawl', v_now)
  limit 1;
  select * into v_r2
  from private.stage1_current_valid_release_artifact('r2_recovery_drill', v_now)
  limit 1;
  select * into v_crop
  from private.stage1_current_valid_release_artifact('visual_crop_coverage', v_now)
  limit 1;

  v_objects := private.stage1_visual_r2_object_set_snapshot();
  v_coverage := private.stage1_visual_crop_coverage_snapshot();
  if v_target ->> 'configured' = 'true' then
    v_leak_manifest := public.get_stage1_release_leak_crawl_manifest();
  else
    v_leak_manifest := '{}'::jsonb;
  end if;
  v_r2_bound := v_runtime.id is not null
    and v_r2.id is not null
    and v_objects ->> 'unexpected_bucket_count' = '0'
    and v_objects ->> 'malformed_object_count' = '0'
    and v_r2.app_revision = v_runtime.app_revision
    and v_r2.evidence ->> 'visual_object_set_hash' =
      v_objects ->> 'visual_object_set_hash'
    and v_r2.evidence ->> 'visual_objects_checked' =
      v_objects ->> 'visual_object_count';
  v_crop_bound := v_runtime.id is not null
    and v_crop.id is not null
    and v_crop.producer_kind = 'database_derived'
    and v_crop.app_revision = v_runtime.app_revision
    and v_crop.evidence ->> 'eligible_events' = v_coverage ->> 'eligible_events'
    and v_crop.evidence ->> 'verified_events' = v_coverage ->> 'verified_events'
    and v_crop.evidence ->> 'unverified_publishable_events' =
      v_coverage ->> 'unverified_publishable_events'
    and v_crop.evidence ->> 'terminal_failures' = v_coverage ->> 'terminal_failures'
    and v_crop.evidence ->> 'pdf_evidence_failures' = v_coverage ->> 'pdf_evidence_failures'
    and v_crop.evidence ->> 'coverage_set_hash' = v_coverage ->> 'coverage_set_hash'
    and v_crop.evidence ->> 'visual_object_count' = v_objects ->> 'visual_object_count'
    and v_crop.evidence ->> 'visual_object_set_hash' = v_objects ->> 'visual_object_set_hash'
    and v_crop.evidence ->> 'derivation_contract_hash' =
      private.stage1_visual_crop_derivation_contract_hash()
    and v_crop.evidence ->> 'r2_hashes_verified' = 'true'
    and v_crop.evidence ->> 'r2_artifact_id' = v_r2.id::text
    and v_r2_bound;
  v_artifacts_ok := v_runtime.id is not null
    and v_rollback.id is not null
    and v_leak.id is not null
    and v_r2_bound
    and v_crop_bound
    and v_rollback.app_revision = v_runtime.app_revision
    and v_leak.app_revision = v_runtime.app_revision
    and v_rollback.evidence ->> 'contract_state_hash' = v_contract_state_hash
    and v_leak.evidence ->> 'route_manifest_sha256' =
      v_leak_manifest ->> 'route_manifest_sha256'
    and pg_catalog.rtrim(v_leak.evidence ->> 'base_url', '/') =
      pg_catalog.rtrim(v_runtime.evidence ->> 'base_url', '/');

  with base_runs as (
    select
      run as worker_run,
      run.*,
      private.stage1_normal_6pm_monitoring_date(run) as monitoring_date,
      case
        when run.metadata #>> '{run_identity,shard_index}' ~ '^[0-2]$'
          then (run.metadata #>> '{run_identity,shard_index}')::integer
        else -1
      end as shard_index
    from public.local_worker_runs run
    where run.started_at <= v_now
      and private.stage1_normal_6pm_monitoring_date(run) between v_due_date - 3 and v_due_date
  ), ranked_runs as (
    select
      base_runs.*,
      pg_catalog.row_number() over (
        partition by monitoring_date, shard_index
        order by started_at desc, id desc
      ) as rank_for_shard
    from base_runs
    where monitoring_date is not null
  ), latest_runs as (
    select * from ranked_runs where rank_for_shard = 1
  ), cohorts as (
    select
      monitoring_date,
      max(finished_at) as finished_at,
      count(*) as shard_count,
      (
        count(*) = 3
        and count(distinct shard_index) = 3
        and pg_catalog.bool_and(private.stage1_6pm_shard_healthy(latest_runs.worker_run))
        and count(distinct (metadata #>> '{source_inventory,global_source_count}')) = 1
        and count(distinct (metadata #>> '{source_inventory,global_source_ids_sha256}')) = 1
        and count(distinct (metadata #> '{source_inventory,partitions}')) = 1
        and sum(case
          when metadata #>> '{source_inventory,expected_shard_source_count}' ~ '^[1-9][0-9]*$'
            then (metadata #>> '{source_inventory,expected_shard_source_count}')::bigint
          else -1000000000
        end) = max(case
          when metadata #>> '{source_inventory,global_source_count}' ~ '^[1-9][0-9]*$'
            then (metadata #>> '{source_inventory,global_source_count}')::bigint
          else -2000000000
        end)
      ) as healthy,
      pg_catalog.jsonb_agg(id order by shard_index) as run_ids,
      max(metadata #>> '{source_inventory,global_source_count}') as global_source_count,
      max(metadata #>> '{source_inventory,global_source_ids_sha256}') as global_source_hash
    from latest_runs
    group by monitoring_date
  ), required_dates as (
    select
      offset_value,
      v_due_date - offset_value as monitoring_date
    from pg_catalog.generate_series(0, 3) offset_value
  ), required as (
    select
      required_dates.offset_value,
      required_dates.monitoring_date,
      cohorts.finished_at,
      coalesce(cohorts.healthy, false) as healthy,
      cohorts.run_ids,
      cohorts.global_source_count,
      cohorts.global_source_hash
    from required_dates
    left join cohorts using (monitoring_date)
  )
  select pg_catalog.jsonb_build_object(
    'contract', 'awardping.stage1.three-6pm-plus-24h-soak.v2',
    'due_monitoring_date', v_due_date,
    'required_acceptance_cohorts', 3,
    'acceptance_cohorts', coalesce((
      select pg_catalog.jsonb_agg(
        pg_catalog.jsonb_build_object(
          'monitoring_date', required.monitoring_date,
          'healthy', required.healthy,
          'finished_at', required.finished_at,
          'run_ids', required.run_ids,
          'global_source_count', required.global_source_count,
          'global_source_hash', required.global_source_hash
        ) order by required.offset_value desc
      )
      from required where required.offset_value between 1 and 3
    ), '[]'::jsonb),
    'healthy_acceptance_cohorts', (
      select count(*) from required
      where offset_value between 1 and 3 and healthy
    ),
    'current_due_cohort_healthy', coalesce((
      select healthy from required where offset_value = 0
    ), false),
    'healthy_required_calendar_dates', (
      select count(*) from required where healthy
    ),
    'soak_started_at', (
      select finished_at from required where offset_value = 1
    ),
    'soak_complete', coalesce((
      select healthy and finished_at is not null
        and v_now - finished_at >= interval '24 hours'
      from required where offset_value = 1
    ), false),
    'app_worker_identity_mismatches', (
      select count(*)
      from latest_runs
      where v_runtime.id is null
        or metadata ->> 'worker_revision' is distinct from v_runtime.app_revision
        or metadata #>> '{monitoring_policy_bundle,hash}' is distinct from
          v_runtime.evidence ->> 'policy_hash'
        or metadata #>> '{monitoring_policy,hash}' is distinct from
          v_runtime.evidence ->> 'batch_policy_hash'
        or metadata #>> '{suppression_policy,hash}' is distinct from
          v_runtime.evidence ->> 'suppression_policy_hash'
        or metadata ->> 'matcher_digest' is distinct from
          v_runtime.evidence ->> 'matcher_hash'
    ),
    'r2_enabled_current_shards', (
      select count(*)
      from latest_runs
      where monitoring_date = v_due_date
        and private.stage1_json_flag_enabled(
          metadata #> '{options,r2_rehydrate_local_cache}'
        )
    ),
    'r2_failed_current', coalesce((
      select sum(case
        when metadata #>> '{counts,r2_rehydration_failed}' ~ '^[0-9]+$'
          then (metadata #>> '{counts,r2_rehydration_failed}')::bigint
        else 1000000 end)
      from latest_runs where monitoring_date = v_due_date
    ), 1000000),
    'r2_refused_current', coalesce((
      select sum(case
        when metadata #>> '{counts,r2_rehydration_refused}' ~ '^[0-9]+$'
          then (metadata #>> '{counts,r2_rehydration_refused}')::bigint
        else 1000000 end)
      from latest_runs where monitoring_date = v_due_date
    ), 1000000),
    'all_bound_run_ids', coalesce((
      select pg_catalog.jsonb_agg(id order by monitoring_date, shard_index)
      from latest_runs
    ), '[]'::jsonb)
  ) into v_nightly;

  v_nightly_ok := v_nightly ->> 'healthy_acceptance_cohorts' = '3'
    and v_nightly ->> 'current_due_cohort_healthy' = 'true'
    and v_nightly ->> 'healthy_required_calendar_dates' = '4'
    and v_nightly ->> 'soak_complete' = 'true'
    and v_nightly ->> 'app_worker_identity_mismatches' = '0'
    and v_nightly ->> 'r2_enabled_current_shards' = '3'
    and v_nightly ->> 'r2_failed_current' = '0'
    and v_nightly ->> 'r2_refused_current' = '0'
    and pg_catalog.jsonb_array_length(v_nightly -> 'all_bound_run_ids') = 12;

  select
    count(*),
    count(*) filter (
      where budget.lane_key in ('new_page_review', 'changed_page_review')
        and budget.cap_micro_usd = 5000000
        and budget.reserved_micro_usd >= 0
        and budget.spent_micro_usd >= 0
        and budget.remaining_micro_usd =
          budget.cap_micro_usd - budget.reserved_micro_usd - budget.spent_micro_usd
        and budget.remaining_micro_usd >= 0
        and budget.reset_at > v_now
        and budget.source = 'postgres_atomic_budget_v1'
    ),
    coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(budget) order by budget.lane_key), '[]'::jsonb)
  into v_budget_count, v_budget_valid_count, v_budgets
  from public.list_gemini_budget_status() budget;
  v_budgets_ok := v_budget_count = 2 and v_budget_valid_count = 2;

  select
    count(*),
    count(*) filter (
      where lane.enabled
        and not lane.lease_expired
        and not lane.sla_breached
        and lane.timeout_seconds > 0
        and lane.lease_ttl_seconds > lane.timeout_seconds
        and private.stage1_downstream_lane_sla_contract_valid(
          lane.lane_key,
          lane.sla_seconds,
          lane.oldest_item_sla_seconds,
          lane.queue_depth,
          lane.oldest_item_at,
          lane.next_sla_due_at
        )
        and lane.source = 'postgres_lane_scheduler_v1'
        and (
          (
            lane.lane_key in ('new_page_review', 'changed_page_review')
            and lane.creates_api_charge
            and lane.paid_lane_key = lane.lane_key
          )
          or (
            lane.lane_key not in ('new_page_review', 'changed_page_review')
            and not lane.creates_api_charge
            and lane.paid_lane_key is null
          )
        )
    ),
    coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(lane) order by lane.lane_key), '[]'::jsonb)
  into v_lane_count, v_lane_valid_count, v_lanes
  from public.list_monitoring_downstream_lane_status() lane;
  v_lanes_ok := v_lane_count = 8 and v_lane_valid_count = 8;

  if v_cohort_count <> 25 or v_cohort_identity_hash <>
    '71aabb42ea22307645038d2b76aa23ea499609d45755b577b8d22298922a2ea9' then
    v_failures := pg_catalog.array_append(v_failures, 'exact_national_25_identity_failed');
  end if;
  if v_target ->> 'configured' <> 'true' then
    v_failures := pg_catalog.array_append(
      v_failures, 'admin_owned_production_target_not_configured'
    );
  end if;
  if v_ready_count <> 25 then
    v_failures := pg_catalog.array_append(v_failures, 'award_readiness_not_25_of_25');
  end if;
  if v_release.release_key is null
    or v_release.release_state = 'verified_beta'
    or v_release.release_epoch is not null
    or v_release.policy_version <> 'stage1-publication-v1' then
    v_failures := pg_catalog.array_append(v_failures, 'release_state_not_closed_or_mismatched');
  end if;
  if v_quarantine_count <> 0 then
    v_failures := pg_catalog.array_append(v_failures, 'actionable_quarantine_remaining');
  end if;
  if not v_contract_ok or not v_invite_acl_ok then
    v_failures := pg_catalog.array_append(v_failures, 'invite_only_database_contract_failed');
  end if;
  if not v_vault_access_contract_safe or not v_vault_service_profile_blocked then
    v_failures := pg_catalog.array_append(v_failures, 'vault_access_contract_failed');
  end if;
  if v_invite_reissue_count <> 0 then
    v_failures := pg_catalog.array_append(v_failures, 'invite_security_reissues_remaining');
  end if;
  if v_runtime.id is null or v_runtime.evidence ->> 'disable_signup' <> 'true' then
    v_failures := pg_catalog.array_append(v_failures, 'signed_hosted_auth_runtime_evidence_missing');
  end if;
  -- OWNER DIRECTIVE 2026-09-02 (Matthew: "publish to the website what you
  -- have now and then update it daily"): the four-night fleet soak is WAIVED
  -- for this activation. The soak/identity status stays computed and reported
  -- in the summary (nightly_soak key) for observability, but no longer blocks
  -- the state. Every other leg - 25/25 readiness, zero actionable
  -- quarantines, invite/vault contracts, all five signed artifacts, crop
  -- coverage, budgets, and the eight downstream lanes - remains enforced.
  -- Restore the original clause to re-arm the soak for future re-releases.
  if not v_nightly_ok then
    null; -- soak waived per the 2026-09-02 owner directive (was: append three_6pm_cohorts_soak_or_runtime_identity_failed)
  end if;
  if not v_budgets_ok then
    v_failures := pg_catalog.array_append(v_failures, 'two_atomic_5_usd_budgets_failed');
  end if;
  if not v_lanes_ok then
    v_failures := pg_catalog.array_append(v_failures, 'eight_downstream_lanes_failed');
  end if;
  if not v_r2_bound then
    v_failures := pg_catalog.array_append(v_failures, 'signed_r2_recovery_or_object_set_failed');
  end if;
  if not v_crop_bound then
    v_failures := pg_catalog.array_append(v_failures, 'database_derived_exact_crop_coverage_failed');
  end if;
  if not v_artifacts_ok then
    v_failures := pg_catalog.array_append(v_failures, 'release_artifact_set_failed');
  end if;

  v_basis := pg_catalog.jsonb_build_object(
    'schema_version', 'stage1-release-gate-acceptance-v2',
    'release_contract_state_hash', v_contract_state_hash,
    'production_target', v_target,
    'cohort', pg_catalog.jsonb_build_object(
      'expected_count', 25,
      'registry_count', v_cohort_count,
      'ready_count', v_ready_count,
      'identity_version', 'stage1-national-25-v3',
      'identity_hash', v_cohort_identity_hash
    ),
    'release', pg_catalog.to_jsonb(v_release),
    'quarantine', pg_catalog.jsonb_build_object(
      'actionable_count', v_quarantine_count
    ),
    'invite', pg_catalog.jsonb_build_object(
      'database_contract', v_contract,
      'database_acl_safe', v_invite_acl_ok,
      'unresolved_security_reissues', v_invite_reissue_count,
      'hosted_runtime_artifact_id', v_runtime.id,
      'disable_signup', v_runtime.evidence -> 'disable_signup'
    ),
    'vault_security', pg_catalog.jsonb_build_object(
      'api_surface_safe', v_vault_access_contract_safe,
      'service_role_data_api_profile_blocked', v_vault_service_profile_blocked,
      'profile_http_status', v_runtime.evidence -> 'vault_profile_http_status',
      'profile_postgrest_code', v_runtime.evidence -> 'vault_profile_postgrest_code'
    ),
    'nightly', v_nightly,
    'budgets', v_budgets,
    'lanes', v_lanes,
    'r2_recovery', pg_catalog.jsonb_build_object(
      'current_worker_configuration_safe', v_nightly_ok,
      'artifact_id', v_r2.id,
      'artifact_evidence_hash', v_r2.evidence_hash,
      'current_object_set', v_objects,
      'bound', v_r2_bound
    ),
    'visual_crop_coverage', v_coverage || pg_catalog.jsonb_build_object(
      'artifact_id', v_crop.id,
      'artifact_evidence_hash', v_crop.evidence_hash,
      'r2_hashes_verified', v_r2_bound,
      'bound', v_crop_bound
    ),
    'artifacts', pg_catalog.jsonb_build_object(
      'hosted_runtime_identity', pg_catalog.jsonb_build_object(
        'id', v_runtime.id, 'evidence_hash', v_runtime.evidence_hash
      ),
      'rollback_drill', pg_catalog.jsonb_build_object(
        'id', v_rollback.id, 'evidence_hash', v_rollback.evidence_hash
      ),
      'non_cohort_leak_crawl', pg_catalog.jsonb_build_object(
        'id', v_leak.id, 'evidence_hash', v_leak.evidence_hash
      ),
      'r2_recovery_drill', pg_catalog.jsonb_build_object(
        'id', v_r2.id, 'evidence_hash', v_r2.evidence_hash
      ),
      'visual_crop_coverage', pg_catalog.jsonb_build_object(
        'id', v_crop.id, 'evidence_hash', v_crop.evidence_hash
      )
    ),
    'failures', pg_catalog.to_jsonb(v_failures)
  );
  v_state_hash := public.stage1_publication_evidence_hash(v_basis);
  return v_basis || pg_catalog.jsonb_build_object(
    'generated_at', v_now,
    'state', case when pg_catalog.cardinality(v_failures) = 0 then 'READY' else 'HOLD' end,
    'state_hash', v_state_hash
  );
end;
$function$

