-- The last two demotion triggers get the released-cohort split (owner
-- directive 2026-09-02/03). invalidate_stage1_publication_on_evidence_change
-- (stage1_award_source_manifest / members / identity_rules) and
-- invalidate_stage1_publication_on_canonical_award_change (shared_awards
-- name / slug / homepage / public_facts / status) demoted a verified_beta
-- cohort without clearing its epoch, which under the activated release
-- violates stage1_registry_release_epoch_state_check and errors the writing
-- statement - blocking set_stage1_award_manifest_entry and the reviewed
-- promotion, i.e. the daily refine chain itself, and any lane writing
-- public_facts for a canonical award. Released cohorts are now flagged and
-- keep serving; unreleased cohorts demote exactly as before.
-- Generated by patching the live definitions; only the marked CTEs changed.

CREATE OR REPLACE FUNCTION public.invalidate_stage1_publication_on_canonical_award_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_invalidated_at timestamptz := now();
  v_evidence jsonb;
  v_invalidated_count integer := 0;
begin
  v_evidence := pg_catalog.jsonb_build_object(
    'trigger_table', tg_table_name,
    'operation', tg_op,
    'shared_award_id', new.id,
    'invalidated_at', v_invalidated_at
  );

  with active_release as (
    select release_state.release_epoch
    from public.stage1_publication_release_state release_state
    where release_state.release_key = 'stage1-national-25'
      and release_state.activated_at is not null
      and release_state.release_state = 'verified_beta'
      and release_state.release_epoch is not null
  ), refreshed_released as (
    -- OWNER DIRECTIVE 2026-09-02/03: released cohorts keep serving while the
    -- change is re-verified (same split as the source / fact-candidate /
    -- reconciliation-outcome invalidators). Before this, the demotion here
    -- violated stage1_registry_release_epoch_state_check under the activated
    -- release and ERRORED the canonical award write itself.
    update public.stage1_award_registry registry
    set
      state_reason = 'Canonical award identity or published facts changed after release; re-verification is scheduled while the last verified publication stays live.',
      updated_at = v_invalidated_at
    from active_release
    where registry.canonical_shared_award_id = new.id
      and registry.publication_state = 'verified_beta'
      and registry.release_epoch = active_release.release_epoch
    returning registry.cohort_key
  ), invalidated as (
    update public.stage1_award_registry registry
    set
      publication_state = 'revalidation_pending',
      state_reason = 'Canonical award identity or published facts changed; fresh Stage 1 verification is required.',
      evidence_checked_at = null,
      updated_at = v_invalidated_at
    where registry.canonical_shared_award_id = new.id
      and registry.publication_state = 'verified_beta'
      and not exists (
        select 1 from active_release
        where active_release.release_epoch = registry.release_epoch
      )
    returning registry.cohort_key, registry.policy_version
  )
  insert into public.stage1_award_publication_events (
    cohort_key,
    previous_state,
    next_state,
    reason,
    policy_version,
    evidence_snapshot,
    evidence_hash,
    actor
  )
  select
    invalidated.cohort_key,
    'verified_beta',
    'revalidation_pending',
    'Canonical award identity or published facts changed; fresh Stage 1 verification is required.',
    invalidated.policy_version,
    v_evidence,
    public.stage1_publication_evidence_hash(v_evidence),
    'database-trigger'
  from invalidated;

  get diagnostics v_invalidated_count = row_count;

  if v_invalidated_count > 0 then
    perform public.invalidate_stage1_cohort_release(
      'Canonical award identity or published facts changed; the 25-award release requires revalidation.',
      'database-trigger'
    );
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.invalidate_stage1_publication_on_evidence_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_cohort_keys text[] := '{}'::text[];
begin
  if tg_op <> 'DELETE' then
    v_cohort_keys := pg_catalog.array_append(v_cohort_keys, new.cohort_key);
  end if;
  if tg_op <> 'INSERT' then
    v_cohort_keys := pg_catalog.array_append(v_cohort_keys, old.cohort_key);
  end if;

  with active_release as (
    select release_state.release_epoch
    from public.stage1_publication_release_state release_state
    where release_state.release_key = 'stage1-national-25'
      and release_state.activated_at is not null
      and release_state.release_state = 'verified_beta'
      and release_state.release_epoch is not null
  ), refreshed_released as (
    -- OWNER DIRECTIVE 2026-09-02/03: released cohorts keep serving while the
    -- evidence change (manifest / members / identity rules - the daily refine
    -- chain's own writes) is re-verified. Before this, the demotion violated
    -- stage1_registry_release_epoch_state_check under the activated release
    -- and ERRORED the evidence write itself, blocking the daily refine chain.
    update public.stage1_award_registry registry
    set
      state_reason = format(
        'Stage 1 evidence changed in %s after release; re-verification is scheduled while the last verified publication stays live.',
        tg_table_name
      ),
      updated_at = now()
    from active_release
    where registry.cohort_key = any(v_cohort_keys)
      and registry.publication_state = 'verified_beta'
      and registry.release_epoch = active_release.release_epoch
    returning registry.cohort_key
  ), invalidated as (
    update public.stage1_award_registry registry
    set
      publication_state = 'revalidation_pending',
      state_reason = format(
        'Stage 1 evidence changed in %s; fresh verification is required.',
        tg_table_name
      ),
      evidence_checked_at = null,
      updated_at = now()
    where registry.cohort_key = any(v_cohort_keys)
      and registry.publication_state = 'verified_beta'
      and not exists (
        select 1 from active_release
        where active_release.release_epoch = registry.release_epoch
      )
    returning registry.cohort_key, registry.policy_version
  )
  insert into public.stage1_award_publication_events (
    cohort_key,
    previous_state,
    next_state,
    reason,
    policy_version,
    evidence_snapshot,
    evidence_hash,
    actor
  )
  select
    invalidated.cohort_key,
    'verified_beta',
    'revalidation_pending',
    format(
      'Stage 1 evidence changed in %s; fresh verification is required.',
      tg_table_name
    ),
    invalidated.policy_version,
    pg_catalog.jsonb_build_object(
      'trigger_table', tg_table_name,
      'operation', tg_op,
      'invalidated_at', now()
    ),
    public.stage1_publication_evidence_hash(
      pg_catalog.jsonb_build_object(
        'trigger_table', tg_table_name,
        'operation', tg_op,
        'invalidated_at', now()
      )
    ),
    'database-trigger'
  from invalidated;

  perform public.invalidate_stage1_cohort_release(
    format(
      'Stage 1 evidence changed in %s; the 25-award release requires revalidation.',
      tg_table_name
    ),
    'database-trigger'
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;
