-- Stage 1 "explicit review required" reconciliation outcomes are no longer
-- actionable quarantines (owner directive 2026-09-02/03, publish now / refine
-- daily). The Reconciliation Lane finishes every Stage 1 canonical queue row
-- 'failed' with error 'stage1_explicit_review_required:<cohort>' because a
-- released cohort's facts are human-reviewed and may not be auto-reconciled.
-- sync_manual_quarantine_registry treated the latest failed row per award as
-- a terminal public-page quarantine ('latest_reconciliation_failed'), opened
-- ~50 such rows per night on Stage 1 awards, and re-opened every one the
-- morning sweep resolved at the next 15-minute sync - the daily ping-pong
-- (255 reopen events on 26 cases in three days). Excluding the prefix in both
-- the requires-action and the resolution predicates lets those cases resolve
-- as 'newer_safe_page_states' at the next sync and never re-open. The signal
-- still lives in the queue row and in stage1_award_registry.state_reason.
-- Generated by patching the live definition; only the two predicates changed.

CREATE OR REPLACE FUNCTION public.sync_manual_quarantine_registry()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
 SET statement_timeout TO '60s'
AS $function$
declare
  v_now timestamptz := clock_timestamp();
  v_result jsonb;
  v_write_count bigint := 0;
begin
  perform pg_advisory_xact_lock(hashtext('awardping-manual-quarantine-sync'));

  with active_awards as (
    select
      award.id,
      award.name,
      award.slug,
      award.official_homepage
    from public.shared_awards award
    where award.status = 'active'
  ),
  latest_audit as (
    select distinct on (audit.shared_award_id)
      audit.*
    from public.shared_award_page_audits audit
    join active_awards award
      on award.id = audit.shared_award_id
    order by audit.shared_award_id, audit.created_at desc, audit.id desc
  ),
  latest_reconciliation as (
    select distinct on (queue.shared_award_id)
      queue.*
    from public.shared_award_reconciliation_queue queue
    join active_awards award
      on award.id = queue.shared_award_id
    order by queue.shared_award_id, queue.created_at desc, queue.id desc
  ),
  page_audit_batch_request_state as (
    select
      attempt.gemini_batch_request_key,
      count(*) filter (
        where attempt.ai_result is null
           or jsonb_typeof(attempt.ai_result) = 'null'
      ) as active_attempt_count,
      count(*) filter (
        where attempt.ai_result is not null
          and jsonb_typeof(attempt.ai_result) <> 'null'
          and attempt.ai_result ->> 'error' in ('invalid_json', 'missing_batch_response')
      ) as retryable_failure_count,
      count(*) filter (
        where attempt.ai_result is not null
          and jsonb_typeof(attempt.ai_result) <> 'null'
          and coalesce(attempt.ai_result ->> 'error', '') not in (
            'invalid_json',
            'missing_batch_response'
          )
      ) as successful_attempt_count,
      jsonb_agg(
        jsonb_build_object(
          'id', attempt.id,
          'audit_status', attempt.audit_status,
          'severity', attempt.severity,
          'model', attempt.model,
          'gemini_batch_name', attempt.gemini_batch_name,
          'gemini_batch_request_key', attempt.gemini_batch_request_key,
          'ai_result', attempt.ai_result,
          'created_at', attempt.created_at,
          'resolved_at', attempt.resolved_at
        )
        order by attempt.created_at, attempt.id
      ) as attempts
    from public.shared_award_page_audits attempt
    join (
      select distinct latest.gemini_batch_request_key
      from latest_audit latest
      where latest.audit_kind = 'gemini_batch'
        and latest.gemini_batch_request_key is not null
    ) latest_request
      on latest_request.gemini_batch_request_key = attempt.gemini_batch_request_key
    where attempt.audit_kind = 'gemini_batch'
      and attempt.gemini_batch_request_key is not null
    group by attempt.gemini_batch_request_key
  ),
  public_page_candidates as (
    select
      award.id as shared_award_id,
      award.name as award_name,
      award.slug as award_slug,
      award.official_homepage,
      audit.id as audit_id,
      audit.audit_kind,
      audit.audit_status,
      audit.severity as audit_severity,
      audit.resolved_at as audit_resolved_at,
      audit.created_at as audit_created_at,
      audit.findings,
      audit.suggested_fixes,
      audit.field_conflicts,
      audit.selected_fact_summary,
      audit.public_page_snapshot,
      audit.model as audit_model,
      audit.gemini_batch_name,
      audit.gemini_batch_request_key,
      audit.ai_result,
      reconciliation.id as reconciliation_id,
      reconciliation.status as reconciliation_status,
      reconciliation.reason as reconciliation_reason,
      reconciliation.error as reconciliation_error,
      reconciliation.metadata as reconciliation_metadata,
      reconciliation.created_at as reconciliation_created_at,
      reconciliation.completed_at as reconciliation_completed_at,
      coalesce(batch_state.active_attempt_count, 0) as audit_active_attempt_count,
      coalesce(batch_state.retryable_failure_count, 0) as audit_retryable_failure_count,
      coalesce(batch_state.successful_attempt_count, 0) as audit_successful_attempt_count,
      coalesce(batch_state.attempts, '[]'::jsonb) as audit_batch_attempts,
      audit.id is not null
        and audit.resolved_at is null
        and audit.audit_status in ('failed', 'needs_review')
        and audit.severity in ('error', 'critical') as audit_requires_action,
      reconciliation.id is not null
        and reconciliation.status = 'failed'
        -- 2026-09-03: a Stage 1 "explicit review required" outcome is the lane
        -- declining to auto-reconcile a released cohort, not a failure. The queue
        -- row and the registry state_reason flag carry the re-verification
        -- signal; it is not an actionable quarantine. Fleet rows never carry
        -- this prefix (it is emitted only for stage1_award_members cohorts).
        and coalesce(reconciliation.error, '') not like 'stage1_explicit_review_required:%' as reconciliation_requires_action,
      audit.id is not null
        and audit.audit_kind = 'gemini_batch'
        and audit.gemini_batch_request_key is not null
        and audit.resolved_at is null
        and audit.audit_status in ('failed', 'needs_review')
        and audit.severity in ('error', 'critical')
        and coalesce(batch_state.retryable_failure_count, 0) >= 2
        and coalesce(batch_state.active_attempt_count, 0) = 0
        and coalesce(batch_state.successful_attempt_count, 0) = 0 as audit_terminal
    from active_awards award
    left join latest_audit audit
      on audit.shared_award_id = award.id
    left join latest_reconciliation reconciliation
      on reconciliation.shared_award_id = award.id
    left join page_audit_batch_request_state batch_state
      on batch_state.gemini_batch_request_key = audit.gemini_batch_request_key
  ),
  public_page_cases as (
    select
      'public-page:' || candidate.shared_award_id::text as quarantine_key,
      'public-page:' || candidate.shared_award_id::text as case_key,
      candidate.*,
      candidate.reconciliation_requires_action or candidate.audit_terminal as terminal,
      jsonb_build_object(
        'audit', case
          when candidate.audit_requires_action then jsonb_build_object(
            'id', candidate.audit_id,
            'kind', candidate.audit_kind,
            'status', candidate.audit_status,
            'severity', candidate.audit_severity,
            'findings', candidate.findings,
            'suggested_fixes', candidate.suggested_fixes,
            'field_conflicts', candidate.field_conflicts,
            'selected_fact_summary', candidate.selected_fact_summary,
            'public_page_snapshot', candidate.public_page_snapshot,
            'model', candidate.audit_model,
            'gemini_batch_name', candidate.gemini_batch_name,
            'gemini_batch_request_key', candidate.gemini_batch_request_key,
            'ai_result', candidate.ai_result,
            'created_at', candidate.audit_created_at
          )
          else null
        end,
        'page_audit_batch_attempts', case
          when candidate.audit_kind = 'gemini_batch'
            and candidate.gemini_batch_request_key is not null then jsonb_build_object(
              'request_key', candidate.gemini_batch_request_key,
              'active_attempt_count', candidate.audit_active_attempt_count,
              'retryable_failure_count', candidate.audit_retryable_failure_count,
              'successful_attempt_count', candidate.audit_successful_attempt_count,
              'retry_limit_reached', candidate.audit_terminal,
              'attempts', candidate.audit_batch_attempts
            )
          else null
        end,
        'latest_reconciliation', case
          when not candidate.reconciliation_requires_action then null
          else jsonb_build_object(
            'id', candidate.reconciliation_id,
            'status', candidate.reconciliation_status,
            'reason', candidate.reconciliation_reason,
            'error', candidate.reconciliation_error,
            'metadata', candidate.reconciliation_metadata,
            'created_at', candidate.reconciliation_created_at,
            'completed_at', candidate.reconciliation_completed_at
          )
        end,
        'award', jsonb_build_object(
          'id', candidate.shared_award_id,
          'name', candidate.award_name,
          'slug', candidate.award_slug,
          'official_homepage', candidate.official_homepage
        )
      ) as evidence
    from public_page_candidates candidate
    where candidate.audit_requires_action
       or candidate.reconciliation_requires_action
  ),
  upserted_public_pages as (
    insert into public.manual_quarantine_registry (
      quarantine_key,
      case_key,
      classification,
      category,
      status,
      requires_action,
      terminal,
      terminal_failure_count,
      severity,
      public_impact,
      owner,
      retry_mode,
      retry_charge,
      title,
      reason_code,
      reason,
      recommended_action,
      shared_award_id,
      primary_source_table,
      primary_source_record_id,
      evidence_record_count,
      evidence,
      evidence_hash,
      first_observed_at,
      last_observed_at,
      quarantined_at,
      resolved_at,
      resolved_by,
      resolution_note
    )
    select
      page.quarantine_key,
      page.case_key,
      'actionable_quarantine',
      'public_page',
      'quarantined',
      true,
      page.terminal,
      case when page.reconciliation_requires_action then 1 else 0 end
        + case when page.audit_terminal then 1 else 0 end,
      'high',
      case when page.reconciliation_requires_action then 'protected' else 'unknown' end,
      'Public page review',
      'operator_after_repair',
      'none',
      coalesce(nullif(page.award_name, ''), 'Unknown award') || ': public page needs review',
      case
        when page.reconciliation_requires_action then 'latest_reconciliation_failed'
        when page.audit_terminal then 'page_audit_retry_limit_reached'
        else 'latest_page_audit_requires_review'
      end,
      coalesce(
        nullif(page.reconciliation_error, ''),
        nullif(page.reconciliation_reason, ''),
        nullif(page.evidence -> 'audit' -> 'findings' -> 0 ->> 'message', ''),
        case
          when page.audit_terminal then
            'The latest deterministic page audit reached its safe retry limit.'
          when page.audit_requires_action then 'The latest public-page audit remains unresolved.'
          else 'The latest public-page reconciliation failed.'
        end
      ),
      case
        when page.reconciliation_requires_action and page.audit_requires_action then
          'Inspect the linked audit and reconciliation evidence, repair this award only, then rerun reconciliation and its page audit.'
        when page.reconciliation_requires_action then
          'Inspect the reconciliation evidence, repair this award only, then rerun reconciliation and its page audit.'
        when page.audit_terminal then
          'Inspect the failed page-audit evidence, repair this award only, then rerun the deterministic no-cost page audit.'
        else
          'Verify whether the critical audit affected published facts, repair this award only, then rerun reconciliation and its page audit.'
      end,
      page.shared_award_id,
      case
        when page.audit_requires_action then 'shared_award_page_audits'
        else 'shared_award_reconciliation_queue'
      end,
      case
        when page.audit_requires_action then page.audit_id
        else page.reconciliation_id
      end,
      case when page.audit_requires_action then 1 else 0 end
        + case when page.reconciliation_requires_action then 1 else 0 end,
      page.evidence,
      public.manual_quarantine_evidence_hash(page.evidence),
      case
        when page.audit_requires_action and page.reconciliation_requires_action then
          least(page.audit_created_at, page.reconciliation_created_at)
        when page.audit_requires_action then page.audit_created_at
        else page.reconciliation_created_at
      end,
      case
        when page.audit_requires_action and page.reconciliation_requires_action then greatest(
          page.audit_created_at,
          coalesce(page.reconciliation_completed_at, page.reconciliation_created_at)
        )
        when page.audit_requires_action then page.audit_created_at
        else coalesce(page.reconciliation_completed_at, page.reconciliation_created_at)
      end,
      v_now,
      null,
      null,
      null
    from public_page_cases page
    on conflict (quarantine_key) do update set
      case_key = excluded.case_key,
      classification = excluded.classification,
      category = excluded.category,
      status = case
        when public.manual_quarantine_registry.status = 'in_review' then 'in_review'
        else 'quarantined'
      end,
      requires_action = excluded.requires_action,
      terminal = excluded.terminal,
      terminal_failure_count = excluded.terminal_failure_count,
      severity = excluded.severity,
      public_impact = excluded.public_impact,
      owner = excluded.owner,
      retry_mode = excluded.retry_mode,
      retry_charge = excluded.retry_charge,
      title = excluded.title,
      reason_code = excluded.reason_code,
      reason = excluded.reason,
      recommended_action = excluded.recommended_action,
      policy_id = 'awardping-manual-quarantine',
      policy_version = '1',
      policy_hash = '4a12c7a0c4e088bca3b5c4b9ef28c6ddb8b108ac8b324c23dbde4aa5e0646ae4',
      shared_award_id = excluded.shared_award_id,
      primary_source_table = excluded.primary_source_table,
      primary_source_record_id = excluded.primary_source_record_id,
      evidence_record_count = excluded.evidence_record_count,
      evidence = excluded.evidence,
      evidence_hash = excluded.evidence_hash,
      first_observed_at = least(
        public.manual_quarantine_registry.first_observed_at,
        excluded.first_observed_at
      ),
      last_observed_at = excluded.last_observed_at,
      quarantined_at = case
        when public.manual_quarantine_registry.status = 'resolved' then v_now
        else public.manual_quarantine_registry.quarantined_at
      end,
      resolved_at = null,
      resolved_by = null,
      resolution_note = null
    where public.manual_quarantine_registry.status = 'resolved'
       or public.manual_quarantine_registry.case_key is distinct from excluded.case_key
       or public.manual_quarantine_registry.classification is distinct from excluded.classification
       or public.manual_quarantine_registry.category is distinct from excluded.category
       or public.manual_quarantine_registry.requires_action is distinct from excluded.requires_action
       or public.manual_quarantine_registry.terminal is distinct from excluded.terminal
       or public.manual_quarantine_registry.terminal_failure_count is distinct from excluded.terminal_failure_count
       or public.manual_quarantine_registry.severity is distinct from excluded.severity
       or public.manual_quarantine_registry.public_impact is distinct from excluded.public_impact
       or public.manual_quarantine_registry.owner is distinct from excluded.owner
       or public.manual_quarantine_registry.retry_mode is distinct from excluded.retry_mode
       or public.manual_quarantine_registry.retry_charge is distinct from excluded.retry_charge
       or public.manual_quarantine_registry.title is distinct from excluded.title
       or public.manual_quarantine_registry.reason_code is distinct from excluded.reason_code
       or public.manual_quarantine_registry.reason is distinct from excluded.reason
       or public.manual_quarantine_registry.recommended_action is distinct from excluded.recommended_action
       or public.manual_quarantine_registry.policy_id is distinct from 'awardping-manual-quarantine'
       or public.manual_quarantine_registry.policy_version is distinct from '1'
       or public.manual_quarantine_registry.policy_hash is distinct from
         '4a12c7a0c4e088bca3b5c4b9ef28c6ddb8b108ac8b324c23dbde4aa5e0646ae4'
       or public.manual_quarantine_registry.shared_award_id is distinct from excluded.shared_award_id
       or public.manual_quarantine_registry.primary_source_table is distinct from excluded.primary_source_table
       or public.manual_quarantine_registry.primary_source_record_id is distinct from excluded.primary_source_record_id
       or public.manual_quarantine_registry.evidence_record_count is distinct from excluded.evidence_record_count
       or public.manual_quarantine_registry.evidence_hash is distinct from excluded.evidence_hash
       or public.manual_quarantine_registry.first_observed_at is distinct from least(
         public.manual_quarantine_registry.first_observed_at,
         excluded.first_observed_at
       )
       or public.manual_quarantine_registry.last_observed_at is distinct from excluded.last_observed_at
       or public.manual_quarantine_registry.resolved_at is not null
       or public.manual_quarantine_registry.resolved_by is not null
       or public.manual_quarantine_registry.resolution_note is not null
    returning id
  )
  select count(*) into v_write_count
  from upserted_public_pages;

  with terminal_visuals as (
    select
      candidate.*,
      award.name as award_name,
      award.slug as award_slug,
      source.title as current_source_title,
      source.display_title as current_display_title,
      source.url as current_source_url,
      coalesce(
        case
          when candidate.worker_metadata ->> 'failure_retry_count' ~ '^[0-9]+$'
            then (candidate.worker_metadata ->> 'failure_retry_count')::integer
        end,
        0
      ) as retry_count
    from public.shared_award_visual_review_candidates candidate
    join public.shared_awards award
      on award.id = candidate.shared_award_id
     and award.status = 'active'
    left join public.shared_award_sources source
      on source.id = candidate.shared_award_source_id
    where candidate.status = 'failed'
      and case
        when lower(btrim(coalesce(candidate.rejection_reason, ''))) = 'missing_batch_response'
          then false
        when lower(btrim(coalesce(candidate.rejection_reason, ''))) =
          'manual_recovery_required_possible_external_batch_created'
          then true
        when coalesce(
          case
            when candidate.worker_metadata ->> 'failure_retry_count' ~ '^[0-9]+$'
              then (candidate.worker_metadata ->> 'failure_retry_count')::integer
          end,
          0
        ) >= 0 then true
        else false
      end
  ),
  visual_cases as (
    select
      visual.*,
      jsonb_build_object(
        'candidate', jsonb_build_object(
          'id', visual.id,
          'candidate_signature', visual.candidate_signature,
          'status', visual.status,
          'rejection_reason', visual.rejection_reason,
          'gemini_batch_name', visual.gemini_batch_name,
          'gemini_batch_request_key', visual.gemini_batch_request_key,
          'model', visual.model,
          'submitted_at', visual.submitted_at,
          'completed_at', visual.completed_at,
          'published_at', visual.published_at,
          'ai_result', visual.ai_result,
          'actual_usage', visual.actual_usage,
          'retry_count', visual.retry_count,
          'estimated_cost_usd', visual.estimated_cost_usd,
          'worker_metadata', visual.worker_metadata,
          'previous_snapshot_ref', visual.previous_snapshot_ref,
          'new_snapshot_ref', visual.new_snapshot_ref,
          'previous_text_hash', visual.previous_text_hash,
          'new_text_hash', visual.new_text_hash,
          'previous_image_hash', visual.previous_image_hash,
          'new_image_hash', visual.new_image_hash,
          'previous_file_hash', visual.previous_file_hash,
          'new_file_hash', visual.new_file_hash,
          'deterministic_diff', visual.deterministic_diff,
          'deterministic_classification', visual.deterministic_classification,
          'prompt_payload', visual.prompt_payload,
          'prompt_context', visual.prompt_context,
          'publication_claim_token', visual.publication_claim_token,
          'publication_claimed_at', visual.publication_claimed_at,
          'created_at', visual.created_at,
          'updated_at', visual.updated_at
        ),
        'award', jsonb_build_object(
          'id', visual.shared_award_id,
          'name', visual.award_name,
          'slug', visual.award_slug
        ),
        'source', jsonb_build_object(
          'id', visual.shared_award_source_id,
          'title', coalesce(
            nullif(visual.current_display_title, ''),
            nullif(visual.current_source_title, ''),
            nullif(visual.source_title, '')
          ),
          'url', coalesce(nullif(visual.current_source_url, ''), visual.source_url)
        )
      ) as evidence
    from terminal_visuals visual
  ),
  upserted_visuals as (
    insert into public.manual_quarantine_registry (
      quarantine_key,
      case_key,
      classification,
      category,
      status,
      requires_action,
      terminal,
      terminal_failure_count,
      severity,
      public_impact,
      owner,
      retry_mode,
      retry_charge,
      title,
      reason_code,
      reason,
      recommended_action,
      shared_award_id,
      shared_award_source_id,
      visual_review_candidate_id,
      primary_source_table,
      primary_source_record_id,
      evidence_record_count,
      evidence,
      evidence_hash,
      first_observed_at,
      last_observed_at,
      quarantined_at,
      resolved_at,
      resolved_by,
      resolution_note
    )
    select
      'visual-review:' || visual.id::text,
      'visual-review:' || visual.id::text,
      'actionable_quarantine',
      'visual_review',
      'quarantined',
      true,
      true,
      1,
      'high',
      'delayed',
      'AI review',
      case
        when lower(btrim(coalesce(visual.rejection_reason, ''))) like 'manual_recovery_required_%'
          then 'operator_before_retry'
        else 'paid_retry_approval_required'
      end,
      case
        when lower(btrim(coalesce(visual.rejection_reason, ''))) like 'manual_recovery_required_%'
          then 'unknown'
        else 'will_charge'
      end,
      coalesce(
        nullif(visual.current_display_title, ''),
        nullif(visual.current_source_title, ''),
        nullif(visual.source_title, ''),
        visual.source_url,
        'Visual review candidate'
      ) || ': visual review is quarantined',
      coalesce(nullif(visual.rejection_reason, ''), 'visual_review_terminal_failure'),
      coalesce(
        nullif(visual.rejection_reason, ''),
        'The visual review reached a terminal failure without a recorded reason.'
      ),
      case
        when lower(btrim(coalesce(visual.rejection_reason, ''))) like 'manual_recovery_required_%'
          then 'Reconcile the possible existing Gemini Batch before any new submission; a blind retry could duplicate a charge.'
        else 'Inspect the immutable candidate evidence and failure history before explicitly approving another paid visual-review attempt.'
      end,
      visual.shared_award_id,
      visual.shared_award_source_id,
      visual.id,
      'shared_award_visual_review_candidates',
      visual.id,
      1,
      visual.evidence,
      public.manual_quarantine_evidence_hash(visual.evidence),
      visual.created_at,
      visual.updated_at,
      v_now,
      null,
      null,
      null
    from visual_cases visual
    on conflict (quarantine_key) do update set
      case_key = excluded.case_key,
      classification = excluded.classification,
      category = excluded.category,
      status = case
        when public.manual_quarantine_registry.status = 'in_review' then 'in_review'
        else 'quarantined'
      end,
      requires_action = true,
      terminal = true,
      terminal_failure_count = 1,
      severity = excluded.severity,
      public_impact = excluded.public_impact,
      owner = excluded.owner,
      retry_mode = excluded.retry_mode,
      retry_charge = excluded.retry_charge,
      title = excluded.title,
      reason_code = excluded.reason_code,
      reason = excluded.reason,
      recommended_action = excluded.recommended_action,
      policy_id = 'awardping-manual-quarantine',
      policy_version = '1',
      policy_hash = '4a12c7a0c4e088bca3b5c4b9ef28c6ddb8b108ac8b324c23dbde4aa5e0646ae4',
      shared_award_id = excluded.shared_award_id,
      shared_award_source_id = excluded.shared_award_source_id,
      visual_review_candidate_id = excluded.visual_review_candidate_id,
      primary_source_table = excluded.primary_source_table,
      primary_source_record_id = excluded.primary_source_record_id,
      evidence_record_count = excluded.evidence_record_count,
      evidence = excluded.evidence,
      evidence_hash = excluded.evidence_hash,
      first_observed_at = least(
        public.manual_quarantine_registry.first_observed_at,
        excluded.first_observed_at
      ),
      last_observed_at = excluded.last_observed_at,
      quarantined_at = case
        when public.manual_quarantine_registry.status = 'resolved' then v_now
        else public.manual_quarantine_registry.quarantined_at
      end,
      resolved_at = null,
      resolved_by = null,
      resolution_note = null
    where public.manual_quarantine_registry.status = 'resolved'
       or public.manual_quarantine_registry.case_key is distinct from excluded.case_key
       or public.manual_quarantine_registry.classification is distinct from excluded.classification
       or public.manual_quarantine_registry.category is distinct from excluded.category
       or public.manual_quarantine_registry.requires_action is distinct from excluded.requires_action
       or public.manual_quarantine_registry.terminal is distinct from excluded.terminal
       or public.manual_quarantine_registry.terminal_failure_count is distinct from excluded.terminal_failure_count
       or public.manual_quarantine_registry.severity is distinct from excluded.severity
       or public.manual_quarantine_registry.public_impact is distinct from excluded.public_impact
       or public.manual_quarantine_registry.owner is distinct from excluded.owner
       or public.manual_quarantine_registry.retry_mode is distinct from excluded.retry_mode
       or public.manual_quarantine_registry.retry_charge is distinct from excluded.retry_charge
       or public.manual_quarantine_registry.title is distinct from excluded.title
       or public.manual_quarantine_registry.reason_code is distinct from excluded.reason_code
       or public.manual_quarantine_registry.reason is distinct from excluded.reason
       or public.manual_quarantine_registry.recommended_action is distinct from excluded.recommended_action
       or public.manual_quarantine_registry.policy_id is distinct from 'awardping-manual-quarantine'
       or public.manual_quarantine_registry.policy_version is distinct from '1'
       or public.manual_quarantine_registry.policy_hash is distinct from
         '4a12c7a0c4e088bca3b5c4b9ef28c6ddb8b108ac8b324c23dbde4aa5e0646ae4'
       or public.manual_quarantine_registry.shared_award_id is distinct from excluded.shared_award_id
       or public.manual_quarantine_registry.primary_source_table is distinct from excluded.primary_source_table
       or public.manual_quarantine_registry.primary_source_record_id is distinct from excluded.primary_source_record_id
       or public.manual_quarantine_registry.evidence_record_count is distinct from excluded.evidence_record_count
       or public.manual_quarantine_registry.evidence_hash is distinct from excluded.evidence_hash
       or public.manual_quarantine_registry.first_observed_at is distinct from least(
         public.manual_quarantine_registry.first_observed_at,
         excluded.first_observed_at
       )
       or public.manual_quarantine_registry.last_observed_at is distinct from excluded.last_observed_at
       or public.manual_quarantine_registry.resolved_at is not null
       or public.manual_quarantine_registry.resolved_by is not null
       or public.manual_quarantine_registry.resolution_note is not null
    returning id
  )
  select count(*) into v_write_count
  from upserted_visuals;

  with public_resolution_cases as (
    select
      registry.id,
      case
        when award.id is null then 'The award record is no longer available.'
        when award.status <> 'active' then 'The award is no longer active.'
        else 'Newer safe page-audit and reconciliation states superseded this quarantine.'
      end as resolution_note,
      registry.evidence || jsonb_build_object(
        'resolution',
        jsonb_strip_nulls(jsonb_build_object(
          'resolved_at', v_now,
          'reason', case
            when award.id is null then 'award_missing'
            when award.status <> 'active' then 'award_inactive'
            else 'newer_safe_page_states'
          end,
          'award_status', award.status,
          'latest_page_audit', case when audit.id is null then null else jsonb_build_object(
            'id', audit.id,
            'audit_status', audit.audit_status,
            'severity', audit.severity,
            'resolved_at', audit.resolved_at,
            'created_at', audit.created_at
          ) end,
          'latest_reconciliation', case when reconciliation.id is null then null else jsonb_build_object(
            'id', reconciliation.id,
            'status', reconciliation.status,
            'reason', reconciliation.reason,
            'error', reconciliation.error,
            'created_at', reconciliation.created_at,
            'completed_at', reconciliation.completed_at
          ) end
        ))
      ) as resolved_evidence
    from public.manual_quarantine_registry registry
    left join public.shared_awards award
      on award.id = registry.shared_award_id
    left join lateral (
      select audit.*
      from public.shared_award_page_audits audit
      where audit.shared_award_id = registry.shared_award_id
      order by audit.created_at desc, audit.id desc
      limit 1
    ) audit on true
    left join lateral (
      select queue.*
      from public.shared_award_reconciliation_queue queue
      where queue.shared_award_id = registry.shared_award_id
      order by queue.created_at desc, queue.id desc
      limit 1
    ) reconciliation on true
    where registry.category = 'public_page'
      and registry.policy_id = 'awardping-manual-quarantine'
      and registry.status in ('quarantined', 'in_review')
      and not coalesce((
        award.status = 'active'
        and (
          (
            audit.id is not null
            and audit.resolved_at is null
            and audit.audit_status in ('failed', 'needs_review')
            and audit.severity in ('error', 'critical')
          )
          or (
            reconciliation.id is not null
            and reconciliation.status = 'failed'
            and coalesce(reconciliation.error, '') not like 'stage1_explicit_review_required:%'
          )
        )
      ), false)
  )
  update public.manual_quarantine_registry registry
  set
    status = 'resolved',
    resolved_at = v_now,
    resolved_by = 'manual-quarantine-sync',
    resolution_note = resolution.resolution_note,
    evidence = resolution.resolved_evidence,
    evidence_hash = public.manual_quarantine_evidence_hash(resolution.resolved_evidence)
  from public_resolution_cases resolution
  where registry.id = resolution.id;

  with visual_resolution_cases as (
    select
      registry.id,
      case
        when candidate.id is null then 'The visual candidate is no longer available.'
        when award.id is null then 'The award record is no longer available.'
        when award.status <> 'active' then 'The award is no longer active.'
        else 'The visual candidate left its terminal failed state.'
      end as resolution_note,
      registry.evidence || jsonb_build_object(
        'resolution',
        jsonb_strip_nulls(jsonb_build_object(
          'resolved_at', v_now,
          'reason', case
            when candidate.id is null then 'visual_candidate_missing'
            when award.id is null then 'award_missing'
            when award.status <> 'active' then 'award_inactive'
            else 'visual_candidate_left_terminal_state'
          end,
          'award_status', award.status,
          'candidate', case when candidate.id is null then null else jsonb_build_object(
            'id', candidate.id,
            'status', candidate.status,
            'rejection_reason', candidate.rejection_reason,
            'failure_retry_count', case
              when candidate.worker_metadata ->> 'failure_retry_count' ~ '^[0-9]+$'
                then (candidate.worker_metadata ->> 'failure_retry_count')::integer
              else 0
            end,
            'worker_metadata', candidate.worker_metadata,
            'updated_at', candidate.updated_at
          ) end
        ))
      ) as resolved_evidence
    from public.manual_quarantine_registry registry
    left join public.shared_award_visual_review_candidates candidate
      on candidate.id = registry.primary_source_record_id
    left join public.shared_awards award
      on award.id = registry.shared_award_id
    where registry.category = 'visual_review'
      and registry.policy_id = 'awardping-manual-quarantine'
      and registry.status in ('quarantined', 'in_review')
      and not coalesce((
        award.status = 'active'
        and candidate.status = 'failed'
        and case
          when lower(btrim(coalesce(candidate.rejection_reason, ''))) = 'missing_batch_response'
            then false
          when lower(btrim(coalesce(candidate.rejection_reason, ''))) =
            'manual_recovery_required_possible_external_batch_created'
            then true
          when coalesce(
            case
              when candidate.worker_metadata ->> 'failure_retry_count' ~ '^[0-9]+$'
                then (candidate.worker_metadata ->> 'failure_retry_count')::integer
            end,
            0
          ) >= 0 then true
          else false
        end
      ), false)
  )
  update public.manual_quarantine_registry registry
  set
    status = 'resolved',
    resolved_at = v_now,
    resolved_by = 'manual-quarantine-sync',
    resolution_note = resolution.resolution_note,
    evidence = resolution.resolved_evidence,
    evidence_hash = public.manual_quarantine_evidence_hash(resolution.resolved_evidence)
  from visual_resolution_cases resolution
  where registry.id = resolution.id;

  v_result := public.refresh_manual_quarantine_registry_state(v_now);
  return v_result;
end;
$function$;
