-- Reconciliation outcomes keep released cohorts serving (owner directive
-- 2026-09-02/03). private.invalidate_stage1_reconciliation_outcome is the one
-- demotion path the release-aware patches (20260902210000, 20260902213500,
-- 20260903150000) did not cover: it runs from the Reconciliation Lane's
-- terminal branch (finish_or_requeue_award_reconciliation_claim) and from
-- commit_award_reconciliation_blocked, and it cleared publication_state,
-- release_epoch and evidence_checked_at on any verified_beta cohort with no
-- activated-release guard. Under the activated release that would have
-- removed the cohort from the live set (cohort_release_epoch_mismatch) and
-- darkened every page at the next refresh - the lane finishes every Stage 1
-- queue row 'failed' (stage1_explicit_review_required) each night.
-- Generated by patching the live definition; only the marked CTEs changed.

CREATE OR REPLACE FUNCTION private.invalidate_stage1_reconciliation_outcome(p_shared_award_id uuid, p_reason text, p_actor text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_invalidated_at timestamptz := pg_catalog.clock_timestamp();
  v_invalidated_count integer := 0;
  v_reason text := coalesce(
    nullif(pg_catalog.btrim(p_reason), ''),
    'A Stage 1 reconciliation outcome requires fresh verification.'
  );
  v_actor text := coalesce(
    nullif(pg_catalog.btrim(p_actor), ''),
    'reconciliation-worker'
  );
  v_evidence jsonb;
begin
  if p_shared_award_id is null then
    return 0;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stage1-national-25-release', 0)
  );

  v_evidence := pg_catalog.jsonb_build_object(
    'trigger_table', 'shared_award_reconciliation_queue',
    'shared_award_id', p_shared_award_id,
    'reason', v_reason,
    'invalidated_at', v_invalidated_at
  );

  with affected as (
    select distinct member.cohort_key
    from public.stage1_award_members member
    where member.shared_award_id = p_shared_award_id
  ), active_release as (
    select release_state.release_epoch
    from public.stage1_publication_release_state release_state
    where release_state.release_key = 'stage1-national-25'
      and release_state.activated_at is not null
      and release_state.release_state = 'verified_beta'
      and release_state.release_epoch is not null
  ), refreshed_released as (
    -- OWNER DIRECTIVE 2026-09-02/03 (publish now, refine daily): a cohort that
    -- is part of the ACTIVATED release keeps serving its last verified
    -- publication while a reconciliation outcome schedules re-verification.
    -- Same split as invalidate_stage1_publication_on_source_change /
    -- _on_fact_candidate_change (20260902210000, 20260902213500,
    -- 20260903150000). Observed 2026-09-03: the nightly Reconciliation Lane
    -- finishes every Stage 1 queue row 'failed' (stage1_explicit_review_
    -- required), which demoted 17 cohorts overnight and would have cleared a
    -- released cohort's epoch - darkening all 25 pages at the next refresh.
    update public.stage1_award_registry registry
    set
      state_reason = v_reason
        || ' Re-verification is scheduled while the last verified publication stays live.',
      updated_at = v_invalidated_at
    from affected, active_release
    where registry.cohort_key = affected.cohort_key
      and registry.publication_state = 'verified_beta'
      and registry.release_epoch = active_release.release_epoch
    returning registry.cohort_key
  ), invalidated as (
    update public.stage1_award_registry registry
    set
      publication_state = 'revalidation_pending',
      release_epoch = null,
      state_reason = v_reason,
      evidence_checked_at = null,
      updated_at = v_invalidated_at
    from affected
    where registry.cohort_key = affected.cohort_key
      and registry.publication_state = 'verified_beta'
      and not exists (
        select 1 from active_release
        where active_release.release_epoch = registry.release_epoch
      )
    returning registry.cohort_key, registry.policy_version
  )
  insert into public.stage1_award_publication_events (
    cohort_key,
    previous_state,
    next_state,
    reason,
    policy_version,
    evidence_snapshot,
    evidence_hash,
    actor
  )
  select
    invalidated.cohort_key,
    'verified_beta',
    'revalidation_pending',
    v_reason,
    invalidated.policy_version,
    v_evidence,
    public.stage1_publication_evidence_hash(v_evidence),
    v_actor
  from invalidated;

  get diagnostics v_invalidated_count = row_count;

  if v_invalidated_count > 0 then
    perform public.invalidate_stage1_cohort_release(v_reason, v_actor);
  end if;

  return v_invalidated_count;
end;
$function$;
